version: '3.5'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
  netty-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: netty-app
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      mongodb:
          condition: service_healthy
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n"
      MONGODB_URI: "mongodb://admin:admin@mongodb:27017/"

volumes:
  mongodb_data: